// <auto-generated />
using System;
using MVP_1B2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVP_1B2.Migrations
{
    [DbContext(typeof(ClientContext))]
    [Migration("20250128065126_MakeServiceIdAndPhotoOptional")]
    partial class MakeServiceIdAndPhotoOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVP_1B2.Models.ClientService", b =>
                {
                    b.Property<Guid>("ClientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClientID", "ServiceID");

                    b.HasIndex("ServiceID");

                    b.ToTable("ClientServices");
                });

            modelBuilder.Entity("MVP_1B2.Models.Person", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Persons");

                    b.HasDiscriminator().HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MVP_1B2.Models.Service", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("MVP_1B2.Models.Client", b =>
                {
                    b.HasBaseType("MVP_1B2.Models.Person");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("MVP_1B2.Models.Employee", b =>
                {
                    b.HasBaseType("MVP_1B2.Models.Person");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ServiceID");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("MVP_1B2.Models.ClientService", b =>
                {
                    b.HasOne("MVP_1B2.Models.Client", "Client")
                        .WithMany("ClientServices")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVP_1B2.Models.Service", "Service")
                        .WithMany("ClientServices")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MVP_1B2.Models.Employee", b =>
                {
                    b.HasOne("MVP_1B2.Models.Service", "Service")
                        .WithMany("Employees")
                        .HasForeignKey("ServiceID");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MVP_1B2.Models.Service", b =>
                {
                    b.Navigation("ClientServices");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("MVP_1B2.Models.Client", b =>
                {
                    b.Navigation("ClientServices");
                });
#pragma warning restore 612, 618
        }
    }
}
